//
//  LocalizedString.swift
//  ThunderSDK
//
//  Created by Thunder SDK Gen on 2024/10/01
//  Copyright @ 2024 Magi, Corporation. All rights reserved.
//
//

import Foundation

/// LocalizedString
/// - Description: 6.0.0 (30a1464a)
public enum LocalizedString: String, CustomStringConvertible, CaseIterable, Identifiable, Codable {
    /// スメーシーワールド
    case Carousel
    /// カタログ
    case CatalogAppName
    /// 引き換えできます
    case CatalogAvailable
    /// ビッグラン開催中！ポイント！
    case CatalogBigrunBonus
    /// カタログレベルを上げてミステリーボックスをゲット！
    case CatalogBonusDescription
    /// レベル10ごとにミステリーボックスをゲットできます
    case CatalogBonusGuide
    /// ボーナス！
    case CatalogBonusTitle
    /// 二つ名
    case CatalogByname
    /// カードパック
    case CatalogCardPack
    /// フレッシュカードパック
    case CatalogCardPackFresh
    /// カードスリーブ
    case CatalogCardSleeve
    /// コンプリート！
    case CatalogComplete
    ///  /
    case CatalogCurrent
    /// Lv.
    case CatalogCurrentExtraLevel
    /// るいけい  p
    case CatalogCurrentPoint
    /// 本日初勝利でもれなくポイントゲット！
    case CatalogDailyBonus
    /// ドリンクチケット
    case CatalogDrinkTicket
    /// エモート
    case CatalogEmote
    /// もうすぐ サービス中！
    case CatalogEndOfSeason
    /// フェス開催中！ポイント！
    case CatalogFesBonus
    /// オキモノ
    case CatalogFigure
    /// フードチケット
    case CatalogFoodTicket
    /// ギアパワーのかけら
    case CatalogGearSkillChip
    /// ゲット！
    case CatalogGot
    ///
    case CatalogGuide
    /// x
    case CatalogItemAmount
    /// カタログレベル
    case CatalogLevel
    ///  まで
    case CatalogLimit
    /// ミステリーボックス
    case CatalogMysteryBox
    /// プレート
    case CatalogNamePlateBg
    /// つぎ
    case CatalogNextBonus
    /// ページ
    case CatalogPage
    ///  /  ページ
    case CatalogPager
    ///  開催中！
    case CatalogPeriod
    /// カタログポイント
    case CatalogPoint
    /// ザッカ屋
    case CatalogSignboard
    /// ステッカー
    case CatalogSticker
    /// カタログ
    case CatalogTitle
    /// イカしたカタログ 配布中！
    case CatalogWelcome
    /// バトルでカタログポイントを貯めてアイテムをゲットしよう！
    case CatalogWelcomeDescription
    /// 旅の途中でテンションバクアゲ～！なグラフィティ見つけたから送るね～
    case ChallengeAboutGraffiti
    /// すべてのチャレンジを支援するために必要なポイントが貯まりました
    case ChallengeAllChallengesCompletable
    /// すべてのチャレンジの支援を達成しました
    case ChallengeAllChallengesCompleted
    /// ワタシたちクマサン商会は、この社会で暮らす全てのみなさんの生活をより豊かにするため、日々イクラ集めに取り組んでいます。「次の旅にはクマサン商会からもぜひ何か協力させてください」と声をかけさせてもらい、今回のコラボレーションが実現しました。
    case ChallengeAnnouncementOfGrizzcoIndustriesStory1
    /// ロブさんの挑戦をバイトで支援していくことは、あなたの人生の新たなやりがいを見つけることにもつながるかもしれません。
    case ChallengeAnnouncementOfGrizzcoIndustriesStory2
    /// ワタシたちクマサン商会は、明るい未来の発展のため、ワタシたちができることを日々考え、行動し続けています。感謝と喜びから始まる社会を目指す。それがワタシたちクマサン商会です。
    case ChallengeAnnouncementOfGrizzcoIndustriesStory3
    /// クマサン商会から旅を愛するみなさんへ
    case ChallengeAnnouncementOfGrizzcoIndustriesTitle
    /// ロブイチ
    case ChallengeAppName
    /// ブラック
    case ChallengeBlack
    /// ブルー
    case ChallengeBlue
    /// チャレンジャー
    case ChallengeChallenger
    /// 支援するチャレンジを選ぶ
    case ChallengeChooseChallenge
    /// 達成しました
    case ChallengeClear
    /// コンプリート！
    case ChallengeComplete
    /// コンプリート特典
    case ChallengeCompleteReward
    /// 支援に使える塗りポイント
    case ChallengeCurrentPoint
    /// ポイント MAX!
    case ChallengeCurrentPointFull
    /// ロブから支援者のみなさまへ
    case ChallengeDearAllOfYou
    /// グラフィティのダウンロード
    case ChallengeDownloadGraffiti
    /// アイコンのダウンロード
    case ChallengeDownloadIcon
    /// 壁紙のダウンロード
    case ChallengeDownloadWallpaper
    /// グリーン
    case ChallengeGreen
    /// お礼のグラフィティをダウンロードできます
    case ChallengeGuideGraffiti
    /// リワードの二つ名をロビー端末から受け取れます
    case ChallengeGuideRewardByName
    /// リワードのアイコンをダウンロードできます
    case ChallengeGuideRewardIcon
    /// リワードの画像をダウンロードできます
    case ChallengeGuideRewardImage
    /// リワードのスリーブをロビー端末から受け取れます
    case ChallengeGuideRewardSleeve
    /// 塗りまくって貯めたポイントでロブの旅を応援しよう！旅の思い出も手に入るかも？！
    case ChallengeHowToPlay
    /// ジャーニー
    case ChallengeJourney
    /// 支援者求ム！
    case ChallengeLookingForSupporters
    /// オレンジ
    case ChallengeOrange
    /// p
    case ChallengePoint
    /// 支援に必要な塗りポイント
    case ChallengePointForSupport
    /// （あと p 不足しています）
    case ChallengePointNotEnough
    /// パープル
    case ChallengePurple
    /// レッド
    case ChallengeRed
    /// コンプリートまで あと
    case ChallengeRemainsOfChallenge
    /// ロブ
    case ChallengeRob
    /// ロブのアゲアゲ旅
    case ChallengeRobJourney
    /// 色を選んでダウンロードしてください
    case ChallengeSelectColor
    /// サイズを選んでダウンロードしてください
    case ChallengeSelectSize
    /// ポイント送信中...
    case ChallengeSendingPoint
    /// みんなアガッてる～？ 孤高のアゲアゲ旅人ロブだよ！その旅のクラウドファンディングなんだ～！
    case ChallengeStory1
    /// 僕がこれまでに立ち寄ったアツアツでアゲアゲなアツアゲスポットを自転車で一周するよ！これってテンションフライハイっしょ？！
    case ChallengeStory2
    /// 旅するなかでバクアゲ～！と思った風景写真や思い出の品は支援してくれたみんなにも送るからね～。そんなこんなでこれからアゲアゲの旅をサクッと始めちゃうんでヨロシク～！
    case ChallengeStory3
    /// 支援する
    case ChallengeSupport
    /// 支援済み
    case ChallengeSupported
    /// ※ 画像の加工や営利目的での利用、再配布はご遠慮ください。
    case ChallengeTermOfUse
    /// ロブイチ
    case ChallengeTitle
    /// 無色
    case ChallengeTransparent
    /// ターコイズ
    case ChallengeTurquoise
    /// ホワイト
    case ChallengeWhite
    /// イエロー
    case ChallengeYellow
    /// p 持っています
    case ChallengeYourPoint
    /// %
    case Common
    /// キャンセル
    case CommonCancel
    /// ガチアサリ
    case CommonClamBlitz
    /// 閉じる
    case CommonClose
    /// :
    case CommonColonRule
    /// ビッグラン
    case CommonCoopBigRun
    /// オカシラ：ランダム
    case CommonCoopBossRandom
    /// ？
    case CommonCoopBossRandomSign
    /// バイトチームコンテスト
    case CommonCoopTeamContest
    /// QRコードは、株式会社デンソーウェーブの登録商標です。
    case CommonCopyrightQrCode
    /// 決定
    case CommonDecide
    /// ダウンロード
    case CommonDownload
    /// おわる
    case CommonEnd
    /// はてな
    case CommonGearPowerBlank
    /// ホーム
    case CommonHome
    /// イカリング３
    case CommonIkaring3
    /// 戻る
    case CommonNavBack
    /// ロード中
    case CommonNowLoading
    /// ひっぱって更新
    case CommonPullToRefresh
    /// ガチホコバトル
    case CommonRainmaker
    /// シェア
    case CommonShare
    /// ガチエリア
    case CommonSplatZones
    /// タイカイサポート
    case CommonTournamentManager
    /// ガチヤグラ
    case CommonTowerControl
    /// トリカラアタック
    case CommonTricolor
    /// トリカラマッチ
    case CommonTricolorMatch
    /// ナワバリバトル
    case CommonTurfWar
    /// はてな
    case CommonWpnNotfound
    /// シフトごとのバイト回数には通信切断などで中断したバイトは含まれません
    case CoopHistoryAnnotation01
    /// 出現数
    case CoopHistoryAvailable
    /// 出現したオカシラシャケ
    case CoopHistoryAvailableBoss
    /// 平均クリアWAVE数
    case CoopHistoryAverageClearWaves
    /// ビッグラン
    case CoopHistoryBigrun
    /// 銅
    case CoopHistoryBigrunBronze
    /// 金
    case CoopHistoryBigrunGold
    /// 銀
    case CoopHistoryBigrunSilver
    /// クリアボーナス
    case CoopHistoryBonus
    /// オカシラシャケ出現！
    case CoopHistoryBossAvailable
    /// Clear!!
    case CoopHistoryClear
    /// 今回のギア
    case CoopHistoryCurrentReward
    /// キケン度
    case CoopHistoryDangerRatio
    /// オカシラシャケ撃破！
    case CoopHistoryDefeatBoss
    /// オカシラシャケを撃退した回数
    case CoopHistoryDefeatBossCount
    /// 倒した！
    case CoopHistoryDefeated
    /// 倒したオオモノシャケ
    case CoopHistoryDefeatedEnemies
    /// ※カッコ内の数字は自分で倒した数です
    case CoopHistoryDefeatedEnemiesGuide
    /// 集めたイクラ
    case CoopHistoryDeliverCount
    /// オオモノシャケ
    case CoopHistoryEnemy
    /// EX-WAVE
    case CoopHistoryExWave
    /// Failure
    case CoopHistoryFailure
    /// GJ!
    case CoopHistoryGj
    /// 集めた金イクラ
    case CoopHistoryGoldenDeliverCount
    /// バイトヒストリー一覧に戻る
    case CoopHistoryGoToStats
    /// ハイスコア
    case CoopHistoryHighestScore
    /// バイトヒストリー
    case CoopHistoryHistory
    /// 獲得ポイント
    case CoopHistoryJobPoint
    /// 評価レート
    case CoopHistoryJobRatio
    /// クマサンポイントカード
    case CoopHistoryKumaPointCard
    /// 最新のバイトへ
    case CoopHistoryLatest
    /// 現在の期間限定ポイント
    case CoopHistoryLimitedPoint
    /// 今月のギア
    case CoopHistoryMonthlyReward
    /// 次のバイト
    case CoopHistoryNext
    /// NG
    case CoopHistoryNg
    /// バイトヒストリーがありません
    case CoopHistoryNoData
    /// バイトヒストリーを表示できません
    case CoopHistoryNotAvailable
    /// 閲覧できるバイトヒストリーは、最新の50戦までです。
    case CoopHistoryNotAvailableDescription
    /// 倒せなかった...
    case CoopHistoryNotDefeated
    /// p
    case CoopHistoryP
    /// バイト回数
    case CoopHistoryPlayCount
    /// バイト
    case CoopHistoryPlayCountBySchedule
    /// 前のバイト
    case CoopHistoryPrevious
    /// プライベート
    case CoopHistoryPrivate
    /// スタッフ募集！
    case CoopHistoryRecruit
    /// 初心者でも安心！元気で明るい方大歓迎！アットホームな職場でアルバイトをしてみませんか？
    case CoopHistoryRecruitDescription
    /// 簡単
    case CoopHistoryRecruitTag1
    /// イクラ集め
    case CoopHistoryRecruitTag2
    /// ～イカした制服でイクラ集め～
    case CoopHistoryRecruitTitle
    /// いつものバイト
    case CoopHistoryRegular
    /// 現在のポイント
    case CoopHistoryRegularPoint
    /// 助けた回数
    case CoopHistoryRescueCount
    /// たすけてもらったかいすう
    case CoopHistoryRescuedCount
    /// ウロコ
    case CoopHistoryScale
    /// ドウウロコ
    case CoopHistoryScaleBronze
    /// キンウロコ
    case CoopHistoryScaleGold
    /// ギンウロコ
    case CoopHistoryScaleSilver
    /// バイトスコア
    case CoopHistoryScore
    /// スケジュールを見る
    case CoopHistorySeeSchedule
    /// オカシラゲージ
    case CoopHistorySmellMeter
    /// 支給ブキ
    case CoopHistorySupplyWeapon
    /// バイトチームコンテスト
    case CoopHistoryTeamContest
    /// サーモンラン
    case CoopHistoryTitle
    /// るいけいポイント
    case CoopHistoryTotalPoint
    /// WAVE
    case CoopHistoryWave
    /// 干潮
    case CoopHistoryWaveLevel0
    /// 普通
    case CoopHistoryWaveLevel1
    /// 満潮
    case CoopHistoryWaveLevel2
    /// バイト
    case CoopRecordAppName
    /// 参加回数：
    case CoopRecordAttended
    /// ビッグラン
    case CoopRecordBigrun
    /// 銅
    case CoopRecordBigrunBronze
    /// 金
    case CoopRecordBigrunGold
    /// 銀
    case CoopRecordBigrunSilver
    /// バイトのきろく
    case CoopRecordCoop
    /// たおした数
    case CoopRecordDefeated
    /// 最高評価
    case CoopRecordHighestJobRate
    /// ハイスコア
    case CoopRecordHighestScore
    /// もっと見る
    case CoopRecordMore
    /// きろくがありません
    case CoopRecordNoData
    /// 上位  %以上
    case CoopRecordRank
    /// 順位
    case CoopRecordRanking
    /// バイトチームコンテスト
    case CoopRecordTeamContest
    /// サーモンランのきろく
    case CoopRecordTitle
    /// バイトツナギ オレンジ
    case Cop001
    /// バイトツナギ グリーン
    case Cop002
    /// バイトツナギ イエロー
    case Cop003
    /// バイトツナギ ピンク
    case Cop004
    /// バイトツナギ ブルー
    case Cop005
    /// バイトツナギ ブラック
    case Cop006
    /// バイトツナギ ホワイト
    case Cop007
    /// バイトウェーダー オレンジ
    case Cop008
    /// バイトウェーダー ブラック
    case Cop009
    /// バイトウェーダー イエロー
    case Cop010
    /// バイトウェーダー ブラウン
    case Cop011
    /// バイトツナギ ドット
    case Cop012
    /// バイトツナギ カモ
    case Cop013
    /// バイトツナギ ニシキ
    case Cop014
    /// バイトウェーダー ピーチ
    case Cop015
    /// バイトウェーダー ライム
    case Cop016
    /// バイトウェーダー ベリー
    case Cop017
    /// バイトツナギ シルバー
    case Cop018
    /// バイトツナギ ゴールド
    case Cop019
    /// バイトツナギ プリズム
    case Cop020
    /// バイトツナギ ブロッカー
    case Cop021
    /// ゴンズイ地区
    case District
    /// ホームに戻る
    case ErrorBackToHome
    /// 非正規のアクセスが確認されたため、サービス利用を停止しています。
    case ErrorBannedUser
    /// 現在利用できません。しばらくお待ちください
    case ErrorCurrentlyNotAvailable
    /// エラー
    case ErrorError
    /// エラーが発生しました
    case ErrorErrorOccurred
    /// 読みこみに失敗しました
    case ErrorErrorReopen
    /// ただいまサーバーのメンテナンス中です。時間をおいて再度アクセスしてください。
    case ErrorMaintenanceDescription
    /// しばらくお待ちください
    case ErrorMaintenanceTitle
    /// 読みこみに失敗しました。通信環境のよいところで再度お試しください。
    case ErrorNetworkNotAvailable
    /// イカリング３を表示できません。しばらく時間をおいてから通信環境の良い場所で再度お試しください。それでもこの画面が表示される場合は、ご利用の環境でイカリング３を利用できない可能性があります。
    case ErrorNotSupported
    /// 再読みこみ
    case ErrorReload
    /// イベントマッチ
    case EventMatchRankingAppName
    /// もっと見る
    case EventMatchRankingMore
    /// ペア
    case EventMatchRankingPair
    /// ランキング
    case EventMatchRankingRanking
    /// ルール確認
    case EventMatchRankingRules
    /// ソロ
    case EventMatchRankingSolo
    /// チーム
    case EventMatchRankingTeam
    /// イベントマッチ
    case EventMatchRankingTitle
    /// トップ100
    case EventMatchRankingTop100
    /// ナンプラー遺跡
    case Factory
    /// %
    case FesRecord
    /// フェス
    case FesRecordAppName
    /// 攻撃
    case FesRecordAttack
    /// へいきん
    case FesRecordAverage
    /// チャレンジ
    case FesRecordChallenge
    /// もうすぐ開催
    case FesRecordComingSoon
    /// こうけん度 チャレンジ
    case FesRecordContributionChallenge
    /// こうけん度 オープン
    case FesRecordContributionRegular
    /// こうけん度 トリカラマッチ
    case FesRecordContributionTricolor
    /// 守備
    case FesRecordDefense
    /// パワー
    case FesRecordFestPower
    /// フェス100ケツ
    case FesRecordFestRanking
    /// ホラガイ獲得個数
    case FesRecordGotHoragai
    /// このアンケートはゲーム内で投票するまで何度でも変更できます。みんなの予定を見て、バンカラ街の広場にある投票所から投票しましょう。
    case FesRecordGuideVote
    /// 参加予定のフレンドはチームが変わることがあります
    case FesRecordGuideWillParticipates
    /// 最高フェスパワー
    case FesRecordHighestFestPower
    /// ホラガイ獲得率
    case FesRecordHoragai
    /// 未定のフレンド
    case FesRecordNotVoted
    /// 開催中！！
    case FesRecordOnGoing
    /// これまでのフェス
    case FesRecordPastFestivals
    /// p
    case FesRecordPoint
    /// アンケート実施中
    case FesRecordPreVoteButton
    /// フレンドの参加予定を見ることができます。みんなでチームを組んで参加しよう！
    case FesRecordPreVoteGuide
    /// みんなどこにする？アンケート実施中
    case FesRecordPreVoteTitle
    ///
    case FesRecordRank
    /// オープン
    case FesRecordRegular
    /// フレンドの参加チームを見る
    case FesRecordSeeAllVotes
    /// フェス100ケツを見る
    case FesRecordSeeFestRanking
    /// フェスのきろく
    case FesRecordTitle
    /// るいけい
    case FesRecordTotal
    /// 合計
    case FesRecordTotalScore
    /// 未定
    case FesRecordUndecided
    /// 参加予定
    case FesRecordVote
    /// 回答済み
    case FesRecordVoted
    /// 投票済み
    case FesRecordVotedInGame
    /// 得票率
    case FesRecordVoteRatio
    /// フレンドの投票状況
    case FesRecordVotingStatus
    /// 結果を集計中です
    case FesRecordWaitingForResult
    /// WIN!
    case FesRecordWin
    /// の勝利！
    case FesRecordWinTeam
    /// あなたのきろく
    case FesRecordYourRecord
    /// 警報発令！シャケの接近に注意！
    case FooterBigrunAnnouncement
    /// 発生中！シャケから街を守れ！
    case FooterBigrunNowOpening
    /// もうすぐ サービス中！
    case FooterEndOfSeason
    /// イベントマッチ：開催中！
    case FooterEventMatchNowOpening
    ///  フェス開催！アンケートに回答してフレンドと一緒に参加しよう！
    case FooterFestAnnouncement
    ///  フェス開催中！広場で投票してフェスTをゲットしよう！
    case FooterFestNowOpening
    /// フレンドリスト
    case FriendListAppName
    /// バイト中
    case FriendListInCoopGame
    /// ナワバトラー
    case FriendListInMiniGame
    /// 試合中
    case FriendListInVsGame
    /// パスワードつき
    case FriendListIsLocked
    /// フレンドのプレイ状況がここに表示されます
    case FriendListNoFriends
    /// オフライン
    case FriendListOffline
    /// オンライン
    case FriendListOnline
    /// 再読みこみ
    case FriendListReload
    /// フレンドリスト
    case FriendListTitle
    /// ボイスチャットかのう
    case FriendListVoiceChatEnabled
    /// ゲソタウン
    case GesoTownAppName
    /// ゲソタウンに戻る
    case GesoTownBackToGesotown
    /// 持っているギア
    case GesoTownCurrentGear
    /// ふだんとは違うが手に入るショップ
    case GesoTownDescription
    /// 本日のピックアップ
    case GesoTownFeature
    /// ピックアップ
    case GesoTownFeatured
    ///  につきやすいギアパワー
    case GesoTownFrequentGearPower
    ///  まで
    case GesoTownLimit
    /// おカネ
    case GesoTownMoney
    /// 次のギア
    case GesoTownNext
    /// 次のピックアップ
    case GesoTownNextFeature
    /// 期限切れ
    case GesoTownNotAvailable
    /// 注文する
    case GesoTownOrder
    /// 注文済み
    case GesoTownOrdered
    /// ご注文はいますぐ！
    case GesoTownOrderNow
    /// 在庫確認中...
    case GesoTownPending
    /// 前のギア
    case GesoTownPrevious
    /// まもなく終了
    case GesoTownRemainAlmostFinished
    /// あと時間
    case GesoTownRemainHour
    /// あと分
    case GesoTownRemainMinute
    /// すでに注文済みのギアがあります
    case GesoTownRemind
    /// 注文済みのギアはキャンセルされます
    case GesoTownRemindCaution
    /// ご注文は、1回につき1コとなります
    case GesoTownRule1
    /// 注文済みのギアは、広場のスパイキーから購入できます
    case GesoTownRule2
    /// 購入前に新しく注文すると、注文済みのギアはキャンセルされます
    case GesoTownRule3
    /// 購入後、新しい注文が可能になります
    case GesoTownRule4
    /// ただいま販売中のギア
    case GesoTownStock
    /// 商品は4時間ごとに入れ替わります
    case GesoTownStockGuide
    /// ゲソタウン
    case GesoTownTitle
    /// 受付できません
    case GesoTownUnableToOrder
    /// この商品は現在取り扱っておりません
    case GesoTownUnableToOrderMessage
    /// かけだし
    case Grade00
    /// はんにんまえ
    case Grade01
    /// いちにんまえ
    case Grade02
    /// じゅくれん
    case Grade03
    /// たつじん
    case Grade04
    /// たつじん＋１
    case Grade05
    /// たつじん＋２
    case Grade06
    /// たつじん＋３
    case Grade07
    /// でんせつ
    case Grade08
    /// かけだし アルバイター
    case GradeArbeiter00
    /// はんにんまえ アルバイター
    case GradeArbeiter01
    /// いちにんまえ アルバイター
    case GradeArbeiter02
    /// じゅくれん アルバイター
    case GradeArbeiter03
    /// たつじん アルバイター
    case GradeArbeiter04
    /// たつじん＋１ アルバイター
    case GradeArbeiter05
    /// たつじん＋２ アルバイター
    case GradeArbeiter06
    /// たつじん＋３ アルバイター
    case GradeArbeiter07
    /// でんせつ アルバイター
    case GradeArbeiter08
    /// １号
    case HeroRecordAgent1
    /// ２号
    case HeroRecordAgent2
    /// サイズを選んでダウンロードしてください
    case HeroRecordAnnotation
    /// ヒーローモード
    case HeroRecordAppName
    /// スナップ写真
    case HeroRecordAreaMemorialPhoto
    /// ボス
    case HeroRecordBossStage
    /// ヒーローモード クリア特典
    case HeroRecordClearReward
    /// オルタナ探索率100% 達成特典
    case HeroRecordNawabariMapCompleteReward
    /// オルタナ探索率
    case HeroRecordNawabariMapProgress
    /// クリアおめでとう！
    case HeroRecordNawabariMapSubCleared
    /// 100%踏破おめでとう！
    case HeroRecordNawabariMapSubComplete
    /// オルタナを100%踏破すると…？
    case HeroRecordNawabariMapSubInProgress
    /// 次へ
    case HeroRecordNext
    /// そうびなし
    case HeroRecordNoEquipments
    /// 前へ
    case HeroRecordPrev
    /// イイ目をしたワカモノ求む！！
    case HeroRecordRecruitment
    /// ヒーローモード をはじめて冒険をすすめよう
    case HeroRecordRecruitmentSub
    /// 探索率
    case HeroRecordSearchRatio
    /// スナップ写真を見る
    case HeroRecordSeePhotograph
    /// サイト
    case HeroRecordSite
    /// みらいユートピアランド
    case HeroRecordSite1
    /// あんしんライフファクトリー
    case HeroRecordSite2
    /// ながいきヤングニュータウン
    case HeroRecordSite3
    /// うめたてドリームランド
    case HeroRecordSite4
    /// あすなろグリーンヒルズ
    case HeroRecordSite5
    /// しあわせリサーチラボ
    case HeroRecordSite6
    /// ヒーローモードのきろく
    case HeroRecordTitle
    /// 特製壁紙
    case HeroRecordWallpaper
    /// すべてのバッジ（）
    case HistoryAllBadges
    /// ヒストリー
    case HistoryAppName
    /// 参加回数：
    case HistoryAttended
    /// バッジ
    case HistoryBadge
    /// バンカラマッチ オープン
    case HistoryBankaraOpen
    /// 銅
    case HistoryBronze
    /// 推定順位
    case HistoryEstimatedRanking
    /// イベントマッチ
    case HistoryEvent
    /// もっともよく使ったブキ
    case HistoryFrequentlyUsedWeapon
    /// 金
    case HistoryGold
    /// 最高ウデマエ
    case HistoryHighestUdemae
    /// 最高Xランキング・最高Xパワー
    case HistoryHighestXranking
    /// 最近 3ヶ月
    case HistoryLatest
    /// 最近ゲットしたバッジ
    case HistoryLatestBadge
    /// 月間
    case HistoryMonthly
    /// ※ Xマッチのきろくはシーズン終了後、集計をしてから公開されます。集計が終わるまで数日かかる場合があります。
    case HistoryPastXmatchAnnotation
    /// ランク
    case HistoryRank
    ///
    case HistoryRanking
    /// シーズン
    case HistorySeason
    /// 表示を減らす
    case HistoryShowLess
    /// もっと見る
    case HistoryShowMore
    /// Xランキングを見る
    case HistoryShowXranking
    /// 銀
    case HistorySilver
    ///  からプレイ（ 更新）
    case HistorySince
    /// サマリー
    case HistorySummary
    /// ヒストリー
    case HistoryTitle
    /// 今まで塗った面積
    case HistoryTotalTurfPoint
    /// 総勝利数
    case HistoryTotalWin
    /// p
    case HistoryTurfPoint
    /// ウデマエ
    case HistoryUdemae
    /// ブキヒストリー
    case HistoryWeapon
    /// ブキ使用率
    case HistoryWeaponUsage
    /// Xマッチ
    case HistoryXmatch
    /// ※アプリをインストールしていない方は、このボタンを押しても開きません
    case LandingCaution
    /// Apple、Appleロゴ、App Storeは、Apple Inc.の商標です。Google Play および Google Play ロゴは Google LLC の商標です。
    case LandingCopyright
    /// App Storeからダウンロード
    case LandingDlAppStore
    /// Google Playで手に入れよう
    case LandingDlGooglePlay
    /// アプリのダウンロードはこちら
    case LandingDownload
    /// Nintendo Switch Online
    case LandingNso
    /// アプリを開く
    case LandingOpenApp
    /// スプラトゥーン3
    case LandingSplatoon3
    /// スマートフォンアプリ『Nintendo Switch Online』を開きます
    case LandingTitle
    /// グランドバンカラアリーナ
    case Manbou
    /// メモリープレーヤー
    case MemoryPlayerAppName
    /// コピーしました
    case MemoryPlayerCopied
    /// バトルメモリーのダウンロード
    case MemoryPlayerDownload
    /// ダウンロード予約に失敗しました
    case MemoryPlayerFailedDownload
    /// ダウンロードしたバトルメモリーはスプラトゥーン3のロビー端末のメモリープレーヤーで再生することができます
    case MemoryPlayerGuide
    /// Loading...
    case MemoryPlayerLoading
    /// 最新の50件を表示しています保存期間は30日です
    case MemoryPlayerNotice
    /// コードを入力
    case MemoryPlayerPlaceholder
    /// ダウンロードコード
    case MemoryPlayerReplayCode
    /// データが見つかりません
    case MemoryPlayerReplayNotAvailable
    /// ダウンロード予約しました
    case MemoryPlayerReservedDownload
    /// 送信
    case MemoryPlayerSend
    /// メモリープレーヤー
    case MemoryPlayerTitle
    /// アップロードしたバトルメモリー
    case MemoryPlayerUploaded
    /// マイコーデをつくる
    case MyOutfitsAdd
    /// + このそうびをマイコーデに追加
    case MyOutfitsAddCurrentEquipments
    /// すべて表示
    case MyOutfitsAll
    /// マイコーデ
    case MyOutfitsAppName
    /// ブランド
    case MyOutfitsBrand
    /// カメラオプション
    case MyOutfitsCameraOption
    /// カメラオプションを隠す
    case MyOutfitsCloseCameraOption
    /// フク
    case MyOutfitsCloth
    /// 現在のそうび
    case MyOutfitsCurrentEquipments
    /// 現在のそうびは最後に対戦を行った内容を表示しています
    case MyOutfitsCurrentEquipmentsGuide
    /// 選択中のギア
    case MyOutfitsCurrentGear
    /// 選択中のブキ
    case MyOutfitsCurrentWeapon
    /// 保存に失敗しました
    case MyOutfitsErrorSave
    /// ケイケン値
    case MyOutfitsExp
    /// 絞り込む
    case MyOutfitsFilter
    /// ギア
    case MyOutfitsGear
    /// ギアパワー
    case MyOutfitsGearPower
    /// 追加ギアパワー1個は、基本ギアパワー0.3個分の効果です
    case MyOutfitsGearPowerAnnotation
    /// マイコーデをつくってみよう
    case MyOutfitsGuide
    /// ギアを選択するとギアパワーの内訳が表示されます
    case MyOutfitsGuideGearPowerButton
    /// マイコーデは5つまで作成することができます
    case MyOutfitsGuideLimitation
    /// ジャイロ操作感度
    case MyOutfitsGyro
    /// ジャイロ操作
    case MyOutfitsGyroControl
    /// 携帯モード
    case MyOutfitsHandheldMode
    /// マイコーデ
    case MyOutfitsHashtag
    /// アタマ
    case MyOutfitsHead
    /// メインウェポン
    case MyOutfitsMain
    /// 一致するギアがありません
    case MyOutfitsNoGears
    /// ノーマル
    case MyOutfitsNormal
    /// 一致するブキがありません
    case MyOutfitsNoWeapons
    /// マイコーデ
    case MyOutfitsNumber
    /// OFF
    case MyOutfitsOff
    /// ON
    case MyOutfitsOn
    /// カメラオプションを表示する
    case MyOutfitsOpenCameraOption
    /// レアド
    case MyOutfitsRarity
    ///  左右操作
    case MyOutfitsRControl
    /// リバース
    case MyOutfitsReverse
    ///  操作感度
    case MyOutfitsRHorizontal
    /// ジャイロ操作OFFの時は無効になります
    case MyOutfitsRHorizontalUnavailable
    ///  上下操作
    case MyOutfitsRVertical
    /// ジャイロ操作ONの時は無効になります
    case MyOutfitsRVerticalUnavailable
    /// 保存
    case MyOutfitsSave
    /// フクを選ぶ
    case MyOutfitsSelectCloth
    /// アタマを選ぶ
    case MyOutfitsSelectHead
    /// クツを選ぶ
    case MyOutfitsSelectShoes
    /// 保存先の選択
    case MyOutfitsSelectSlot
    /// ブキを選ぶ
    case MyOutfitsSelectWeapon
    /// シェア
    case MyOutfitsShare
    /// クツ
    case MyOutfitsShoes
    /// スペシャルウェポン
    case MyOutfitsSpecial
    /// サブウェポン
    case MyOutfitsSub
    /// 決定
    case MyOutfitsSubmitGear
    /// 決定
    case MyOutfitsSubmitWeapon
    /// マイコーデ
    case MyOutfitsTitle
    /// 今まで塗った面積
    case MyOutfitsTurfPoint
    /// TVモード/テーブルモード
    case MyOutfitsTvTabletopMode
    /// ブキ
    case MyOutfitsWeapon
    /// 写真は20枚までアップロードできます保存期間は3ヶ月です
    case PhotoAlbumAnnotation
    /// アルバム
    case PhotoAlbumAppName
    /// 選択
    case PhotoAlbumSelect
    /// フォトアルバム
    case PhotoAlbumTitle
    /// QRコードリーダー
    case QrCodeReaderAppName
    /// 日時:
    case QrCodeReaderCheckinDate
    /// 許可
    case QrCodeReaderConfirmationAllow
    /// 許可しない
    case QrCodeReaderConfirmationDeny
    /// このほうしゅうはすでに獲得済みです
    case QrCodeReaderErrorAlreadyGotDescription
    /// すでに獲得しています
    case QrCodeReaderErrorAlreadyGotTitle
    /// イカリング３で読み取ることのできるQRコードではありません
    case QrCodeReaderErrorNotCompatibleDescription
    /// エラー
    case QrCodeReaderErrorNotCompatibleTitle
    /// まだご利用いただけません
    case QrCodeReaderErrorNotStartedTitle
    /// このQRコードはすでに無効です
    case QrCodeReaderErrorRewardExpiredDescription
    /// 有効期間中にお使いください
    case QrCodeReaderErrorRewardNotStartedDescription
    /// イカリング３のQRコード読み取り機能がご利用いただけます。以下のお客様の選択は保存されず、QRコードの読み取りをご利用いただくたびにお客様の同意（GDPR【第】6条【第】1項(a))が求められます。
    case QrCodeReaderEuConfirmation
    /// 特定の場所にあるQRコードを読み取ると特別なほうしゅうをゲットできます
    case QrCodeReaderGuide
    /// 履歴
    case QrCodeReaderHistory
    /// ほうしゅうの受け取りはスプラトゥーン3のロビー端末を使ってね
    case QrCodeReaderHowToGetReward
    /// これまでの読み取り履歴が表示されます
    case QrCodeReaderNoData
    /// カメラでQRコードを読み取る
    case QrCodeReaderReadQrcodeByCamera
    /// 保存した画像から読み取る
    case QrCodeReaderReadQrcodeByFile
    /// QRコードリーダー
    case QrCodeReaderTitle
    /// 各地で同時発生
    case Random
    /// 最後に遊んだ
    case RecordLatestPlayed
    /// よく使う
    case RecordLatestUsed
    /// メイン
    case RecordMain
    /// じゅくれん度アップまで
    case RecordNextSkillLevel
    /// じゅくれん度
    case RecordSkillLevel
    /// 並べ替え
    case RecordSort
    /// スペシャル
    case RecordSpecial
    /// ステージのきろく
    case RecordStageRecord
    /// ステージ
    case RecordStageRecordAppName
    /// サブ
    case RecordSub
    /// きろく
    case RecordTitle
    /// p
    case RecordTotalTurfPoint
    /// 塗りポイント
    case RecordTurfPoint
    /// 遊んでないステージ
    case RecordUnplayedStages
    /// 未所持のブキ
    case RecordUnusedWeapons
    /// チョーシ
    case RecordVibes
    /// ブキのきろく
    case RecordWeaponRecord
    /// ブキ
    case RecordWeaponRecordAppName
    /// 勝利数
    case RecordWinCount
    /// %
    case RecordWinRatio
    /// 通常のプライベートマッチと異なり、招待URLを知っているプレイヤーは誰でも参加することができます。
    case RoomCreatorAnnotation01
    /// フレンドやチャンネルのメンバーは招待URLを知らなくてもフレンドリストや通知からこの部屋に合流することが可能です。
    case RoomCreatorAnnotation02
    /// また、この部屋ではボイスチャットを利用できません。
    case RoomCreatorAnnotation03
    /// 作った部屋に誰も入っていない状態が30分以上続くと、自動的に部屋が閉じられます。
    case RoomCreatorAnnotation04
    /// ヘヤタテ
    case RoomCreatorAppName
    /// 部屋に参加する
    case RoomCreatorApprove
    /// ホームに戻る
    case RoomCreatorBack
    /// やっぱりやめる
    case RoomCreatorCancel
    /// 部屋を解散する
    case RoomCreatorCloseRoom
    /// イカリング３で作った部屋を解散し、招待URLが無効になります。
    case RoomCreatorCloseRoomGuide
    /// 部屋を解散しますか？
    case RoomCreatorConfirmCloseRoom
    /// あなたはすでにヘヤタテで部屋を作っています。あなたの部屋を解散し、この部屋に参加しますか？
    case RoomCreatorConfirmRemoveRoom
    /// 参加しない
    case RoomCreatorConfirmRemoveRoomCancel
    /// 参加する
    case RoomCreatorConfirmRemoveRoomOk
    /// キャンセルしました
    case RoomCreatorDecline
    /// もう一度招待URLにアクセスすると、部屋に参加することができます。
    case RoomCreatorDeclineGuide
    /// すでに部屋を作っています。「ヘヤタテ」で作ることのできる部屋は同時にひとつまでです。
    case RoomCreatorErrorAlreadyExist
    /// 部屋を作ることができませんでした。
    case RoomCreatorErrorMakeRoom
    /// 部屋のURLをシェアして、プライベートマッチに招待することができます。
    case RoomCreatorGuide
    /// 部屋に入る
    case RoomCreatorHowToActivate
    /// スプラトゥーン3のロビーメニューのフレンドリストに追加された「イカリング３で作った部屋」に入ってください。
    case RoomCreatorHowToActivateGuide
    /// フレンドリストから、この部屋に合流してください。
    case RoomCreatorHowToJoin
    /// 解散する
    case RoomCreatorInvalidateInvitation
    /// 部屋に招待されました
    case RoomCreatorInvitation
    /// 部屋に参加するとスプラトゥーン3のフレンドリストに「イカリング３で作った部屋」が追加されます。
    case RoomCreatorInvitationGuide
    /// 招待URL
    case RoomCreatorInvitationUrl
    /// 部屋ができました
    case RoomCreatorInviteGuest
    /// 部屋をつくる
    case RoomCreatorMakeRoom
    /// 部屋が見つかりません
    case RoomCreatorNotFound
    /// URLが間違っているか、すでに部屋が閉じられている場合があります。
    case RoomCreatorNotFoundGuide
    /// パスワードを設定する
    case RoomCreatorPassword
    /// パスワードを設定しない
    case RoomCreatorPasswordCancel
    /// このパスワードはフレンドやチャンネルのメンバーが招待URLを使わずに部屋に合流する場合に必要です。「イカリング３で作った部屋」から入る場合はパスワードは不要です。
    case RoomCreatorPasswordGuide
    /// 4桁の数字を入力してください
    case RoomCreatorPasswordHelp
    /// 参加できる部屋
    case RoomCreatorRoom
    /// 招待したい人にURLをシェア！
    case RoomCreatorShareInvitationUrl
    /// Nintendo Switch Onlineアプリがインストールされたスマートフォンで、招待URLにアクセスしてもらいましょう。
    case RoomCreatorShareInvitationUrlGuide
    /// URLをシェア
    case RoomCreatorShareUrl
    /// 便利な部屋作成サービス
    case RoomCreatorSubtitle
    /// ヘヤタテ
    case RoomCreatorTitle
    /// テッキュウ
    case SakeArtillery
    /// ドロシャケ
    case SakeBigMouth
    /// ドロシャケ
    case SakeBigMouthGold
    /// シャケコプター
    case SakeCopter
    /// モグラ
    case Sakediver
    /// ダイバー
    case SakeDolphin
    /// グリル
    case Sakedozer
    /// タマヒロイ
    case SakeFlyBagman
    /// ジョー
    case SakeJaw
    /// バクダン
    case SakelienBomber
    /// カタパッド
    case SakelienCupTwins
    /// ヨコヅナ
    case SakelienGiant
    /// キンシャケ
    case SakelienGolden
    /// ドスコイ
    case SakelienLarge
    /// テッパン
    case SakelienShield
    /// コジャケ
    case SakelienSmall
    /// ヘビ
    case SakelienSnake
    /// シャケ
    case SakelienStandard
    /// タワー
    case SakelienTower
    /// ハシラ
    case SakePillar
    /// コウモリ
    case Sakerocket
    /// タツ
    case SakeRope
    /// ナベブタ
    case SakeSaucer
    /// タラポートショッピングパーク
    case Section
    /// 利用データの送信について
    case SettingsAboutSendingUsageData
    /// イカリング３をご利用の際には、『Nintendo Switch Online』アプリの「利用データの送信について」の設定が適用されます。この設定はいつでも変更することができます。
    case SettingsAboutSendingUsageDataDescription
    /// 権利表記
    case SettingsAcknowledgements
    /// 設定
    case SettingsAppName
    /// クレジット
    case SettingsCredits
    /// エキスパンション・パス 購入サイトへ
    case SettingsExpansionPass
    /// 設定
    case SettingsTitle
    /// ムニ・エール海洋発電所
    case Shakedent
    /// すじこジャンクション跡
    case Shakehighway
    /// トキシラズいぶし工房
    case Shakelift
    /// どんぴこ闘技場
    case Shakerail
    /// 難破船ドン・ブラコ
    case Shakeship
    /// アラマキ砦
    case Shakespiral
    /// シェケナダム
    case Shakeup
    /// パレットにセットした枚数:
    case SideOrderRecordAccumulateCount
    /// サイド・オーダー
    case SideOrderRecordAppName
    /// ドローン
    case SideOrderRecordChipCategoryAuto
    /// サポート
    case SideOrderRecordChipCategoryContinuity
    /// パワー
    case SideOrderRecordChipCategoryFire
    /// ラッキー
    case SideOrderRecordChipCategoryLuck
    /// ムーブ
    case SideOrderRecordChipCategoryMove
    /// レンジ
    case SideOrderRecordChipCategoryRange
    /// 集めた情報
    case SideOrderRecordChiplevel
    /// クリア！
    case SideOrderRecordClear
    /// クリア:
    case SideOrderRecordClearCount
    /// 集めたカラーチップ
    case SideOrderRecordCollectedColorChips
    /// カッコ内は今までに集めた枚数です
    case SideOrderRecordCollectedColorChipsAnnotation
    /// 集めたパレット
    case SideOrderRecordCollectedPalettes
    /// すべてのパレットでクリアして 特別なほうしゅうをゲット！
    case SideOrderRecordCollectedPalettesSubtitle
    /// カラーチップ
    case SideOrderRecordColorChip
    /// チップ使用率
    case SideOrderRecordColorChipUsage
    /// かんたん
    case SideOrderRecordDifficulity0
    /// ふつう
    case SideOrderRecordDifficulity1
    /// むずかしい
    case SideOrderRecordDifficulity2
    /// ゲキムズ
    case SideOrderRecordDifficulity3
    /// ほうしゅうをゲット！
    case SideOrderRecordDownloadReward
    /// ずかん
    case SideOrderRecordEnemy
    /// スケルトーンずかん
    case SideOrderRecordEnemyCollection
    /// に 当たってやられた
    case SideOrderRecordFailureCollided
    /// に やられた
    case SideOrderRecordFailureDefeated
    /// フロアから 落ちた
    case SideOrderRecordFailureFall
    ///
    case SideOrderRecordFloor
    /// クリア特典
    case SideOrderRecordGetClearReward
    /// コンプリート特典
    case SideOrderRecordGetReward
    /// イイダのハッキング
    case SideOrderRecordHacking
    /// ハイスコア！
    case SideOrderRecordHighScore
    /// 最近のきろく
    case SideOrderRecordLatestResults
    /// もっと見る
    case SideOrderRecordMore
    /// 次へ
    case SideOrderRecordNext
    /// パレット
    case SideOrderRecordPalette
    /// 各パレットの最速クリアタイムのきろくを表示します
    case SideOrderRecordPalettesAnnotation
    /// p
    case SideOrderRecordPoint
    /// 所持ネリコイン
    case SideOrderRecordPointCoin
    /// カラフルカラーチップボーナス
    case SideOrderRecordPointColorful
    /// クリア時ライフ
    case SideOrderRecordPointRetry
    /// 連続同色カラーチップボーナス
    case SideOrderRecordPointSameColor
    /// ポイント→シンジュ
    case SideOrderRecordPointToPearl
    /// 前へ
    case SideOrderRecordPrev
    /// きろく
    case SideOrderRecordResult
    /// あきらめた
    case SideOrderRecordRetire
    /// SCORE
    case SideOrderRecordScore
    /// サイズを選んでダウンロードしてください
    case SideOrderRecordSelectSize
    /// 入手ポイントを表示する
    case SideOrderRecordShowAllPoints
    /// フロアリセット:
    case SideOrderRecordStageReset
    /// サイド・オーダーのきろく
    case SideOrderRecordTitle
    /// 合計:
    case SideOrderRecordTotalHackingLevel
    /// トライ:
    case SideOrderRecordTryCount
    /// 自販機で使ったネリコイン:
    case SideOrderRecordUsedCoin
    /// バンカラマッチ
    case StageScheduleBankara
    /// オープン
    case StageScheduleBankaraOpen
    /// チャレンジ
    case StageScheduleBankaraOpenChallenge
    /// サーモンラン
    case StageScheduleCoop
    /// イベントマッチ
    case StageScheduleEvent
    /// いま
    case StageScheduleEventCurrentSchedule
    /// そのつぎ
    case StageScheduleEventFuture
    /// 開催中！
    case StageScheduleEventHolding
    /// 次回
    case StageScheduleEventNext
    /// つぎ
    case StageScheduleEventNextSchedule
    /// スケジュールが未定です
    case StageScheduleEventNoData
    /// ?????
    case StageScheduleEventUnknownData
    /// チャレンジ
    case StageScheduleFestChallenge
    /// フェスマッチ
    case StageScheduleFestival
    /// もうすぐ開催
    case StageScheduleFestivalAnnounced
    ///  スタート！
    case StageScheduleFestivalAt
    /// 攻撃
    case StageScheduleFestivalAttack
    /// 守備
    case StageScheduleFestivalDefense
    /// 開催中！
    case StageScheduleFestivalHolding
    ///  -
    case StageScheduleFestivalPeriod
    /// オープン
    case StageScheduleFestOpen
    /// そのつぎ
    case StageScheduleFuture
    /// トリカラマッチ時間割
    case StageScheduleGrandFestSchedule
    /// Webブラウザが開きます
    case StageScheduleGuideOpenBrowser
    /// つぎ
    case StageScheduleNext
    /// ビッグラン接近中！
    case StageScheduleNoticeBigrun
    /// バイトチームコンテスト開催予告！
    case StageScheduleNoticeLimited
    /// フェスマッチ開催中！
    case StageScheduleNowClosed
    /// オープン！
    case StageScheduleOpen
    /// ビッグラン発生中！
    case StageScheduleOpenBigrun
    /// バイトチームコンテスト開催中！
    case StageScheduleOpenLimited
    /// プライベートマッチ
    case StageSchedulePrivate
    /// ビッグランがやってくる！！バイト大募集
    case StageScheduleRecruit
    /// バイトチームコンテスト！チームを組んで参加しよう！
    case StageScheduleRecruitTeamContest
    /// レギュラーマッチ
    case StageScheduleRegular
    /// ルールを見る
    case StageScheduleRules
    /// 詳しいルールはこちら
    case StageScheduleSeeAllRules
    /// フェスのきろくを見る
    case StageScheduleSeeFestivalRecord
    /// ランダム
    case StageScheduleSuppliedWeaponRandom
    /// 支給ブキ
    case StageScheduleSuppliedWeapons
    /// スケジュール
    case StageScheduleTitle
    /// ルールごとの勝率
    case StageScheduleWinRateByRules
    /// Xマッチ
    case StageScheduleXmatch
    /// マテガイ放水路
    case Temple
    /// もうすぐ開催！
    case TournamentComingSoon
    /// タイカイサポート
    case TournamentTitle
    /// 開催中
    case TournamentTournamentNow
    /// オカシラ連合
    case Triple
    /// アラマキ砦
    case Tutorial
    /// ？？？
    case Unknown
    /// 海女美術大学
    case Upland
    /// １００倍マッチ
    case VsHistory100X
    /// １０倍マッチ
    case VsHistory10X
    /// １０倍ホラガイ争奪戦
    case VsHistory10XHoragaiMatch
    /// ３３３倍マッチ
    case VsHistory333X
    /// ３３倍ホラガイ争奪戦
    case VsHistory33XHoragaiMatch
    /// 計測中止
    case VsHistoryAbortedMeasurementEventPower
    /// 通信を切断したプレイヤーがいたため、負けとしてカウントされませんでした
    case VsHistoryAnnotationExemption
    /// 無効試合になりました
    case VsHistoryAnnotationNocontest
    /// 正常に試合が終了しませんでした
    case VsHistoryAnnotationPenalty
    /// 攻撃
    case VsHistoryAttack
    /// 分あたりのアベレージ
    case VsHistoryAverage
    /// きん
    case VsHistoryAwardGold
    /// ぎん
    case VsHistoryAwardSilver
    /// バンカラマッチ
    case VsHistoryBankara
    /// バンカラマッチ チャレンジ
    case VsHistoryBankaraChallenge
    /// バンカラマッチ オープン
    case VsHistoryBankaraOpen
    /// バンカラパワー
    case VsHistoryBankaraPower
    /// こうけん度
    case VsHistoryContribute
    /// カウント
    case VsHistoryCount
    /// たおされたかいすう
    case VsHistoryDeathCount
    /// 守備
    case VsHistoryDefense
    /// DRAW
    case VsHistoryDraw
    /// そうびしていたギア
    case VsHistoryEquippedGear
    /// そうびしていたブキ
    case VsHistoryEquippedWeapon
    /// イベントマッチ
    case VsHistoryEvent
    /// ペア
    case VsHistoryEventPair
    /// イベントパワー
    case VsHistoryEventPower
    /// ソロ
    case VsHistoryEventSolo
    /// チーム
    case VsHistoryEventTeam
    /// チーム
    case VsHistoryFesTeam
    /// フェスマッチ
    case VsHistoryFestival
    /// オマツリガイ x
    case VsHistoryFestivalShell
    /// パワー
    case VsHistoryFestPower
    /// オマツリのあかし
    case VsHistoryFesWinProof
    /// ゲットした表彰
    case VsHistoryGotAwards
    /// バトルのきろくに戻る
    case VsHistoryGoToStats
    /// ぬりまといかくほ
    case VsHistoryGotTricolorTreasure
    /// ホラガイ
    case VsHistoryHoragai
    /// Get!
    case VsHistoryHoragaiCount
    /// ホラガイ争奪戦
    case VsHistoryHoragaiMatch
    /// 挑戦中
    case VsHistoryInChallenge
    /// たおしたかいすう
    case VsHistoryKillCount
    /// ノックアウト！
    case VsHistoryKnockout
    /// 最近の50戦
    case VsHistoryLatest
    /// 最新のバトル
    case VsHistoryLatestBattle
    /// 最近
    case VsHistoryLatestTab
    /// LOSE...
    case VsHistoryLose
    /// Xパワー計測中
    case VsHistoryMeasurement
    /// 計測中
    case VsHistoryMeasurementEventPower
    /// 次のバトル
    case VsHistoryNextBattle
    /// バトルのきろくがありません
    case VsHistoryNoData
    /// バトルのきろくを表示できません
    case VsHistoryNotAvailable
    /// 閲覧できるバトルのきろくは、モードごとに最新の50戦までです。
    case VsHistoryNotAvailableDescription
    /// （おそろいボーナス x）
    case VsHistoryOutfitBonus
    /// 前のバトル
    case VsHistoryPreviousBattle
    /// プライベートマッチ
    case VsHistoryPrivate
    /// 昇格戦
    case VsHistoryPromo
    /// レギュラーマッチ
    case VsHistoryRegular
    /// スペシャルウェポンはつどうかいすう
    case VsHistorySpCount
    /// バトル
    case VsHistoryTitle
    /// トライかいすう
    case VsHistoryTryCount
    /// p
    case VsHistoryTurfPoint
    /// ウデマエポイント
    case VsHistoryUdemaePoint
    /// p
    case VsHistoryUdemaePointScore
    /// 挑戦中止
    case VsHistoryUdemaeReset
    /// ウデマエアップ！
    case VsHistoryUdemaeUp
    /// WIN!
    case VsHistoryWin
    /// 連勝
    case VsHistoryWins
    /// おうかん
    case VsHistoryXcrown
    /// Xマッチ
    case VsHistoryXmatch
    /// Xパワー
    case VsHistoryXpower
    /// イカリング３はスプラトゥーン3と連動するサービスです。ここで紹介したもの以外にもさまざまな機能があります。
    case WelcomeAbout
    /// バトルの戦績やスケジュールをチェックしてライバルに差をつけろ！
    case WelcomeFeature1
    /// バトルの戦績やスケジュール
    case WelcomeFeature1Alt
    /// ファッションリーダーたちに朗報！いつでもマイコーデを編集できるぞ！
    case WelcomeFeature2
    /// ひとり旅に出たロブを支援して特別な報酬をゲットしよう！
    case WelcomeFeature3
    /// ここだけの特別仕様！ゲソタウンで限定ギアをチェック！
    case WelcomeFeature4
    /// Features
    case WelcomeFeatures
    /// https://store-jp.nintendo.com/list/software/70010000046394.html
    case WelcomeLink
    /// 他にも便利な機能がたくさん！
    case WelcomeOtherFeatures
    /// 本気のヤツらのためのイカしたサービス
    case WelcomeService
    /// スプラトゥーン3
    case WelcomeSplatoon3
    /// 購入サイトへ
    case WelcomeStore
    /// ウィジェット
    case WelcomeWidgets
    /// すべて表示
    case XRankingAll
    /// Xランキング
    case XRankingAppName
    /// グループ・アロメ
    case XRankingAtlantic
    /// 推定位
    case XRankingEstimatedRank
    /// 計測中
    case XRankingMeasurement
    /// 開催中！！
    case XRankingOpen
    /// グループ・ヤコ
    case XRankingPacific
    /// 過去のランキング
    case XRankingPastRankings
    /// ※ 過去のランキングはシーズン終了後、集計をしてから公開されます。集計が終わるまで数日かかる場合があります。
    case XRankingPastRankingsAnnotation
    ///  -
    case XRankingPeriod
    ///
    case XRankingRank
    ///
    case XRankingRankSns
    /// グループ
    case XRankingRegion
    /// ランキングを見る
    case XRankingSeeRanking
    /// ブキトップを見る
    case XRankingSeeWeaponTop
    /// ブキを選ぶ
    case XRankingSelectWeapon
    /// Xランキング
    case XRankingTitle
    /// トップ 500
    case XRankingTop500
    /// トッププレイヤー
    case XRankingTopPlayers
    /// ブキトップ プレイヤー
    case XRankingWeaponTop
    /// ブキトップ プレイヤー
    case XRankingWeaponTopSingular
    /// おうかん
    case XRankingXcrown
    ///
    case XRankingXpower

    // MARK: Public

    public var id: RawValue { rawValue }
    public var description: String { NSLocalizedString(rawValue, bundle: .module, comment: "") }
}
