services:
  gen:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: source_gen 
    volumes:
      - ../:/home/bun/app:cached
      - node_modules_cached:/home/bun/app/node_modules
    tty: true
    stdin_open: true

volumes:
  node_modules_cached:
