# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    begin
      # 最新のタグを取得
      latest_tag = `git describe --tags --abbrev=0 2>/dev/null`.strip
  
      # タグが存在しない場合は全てのコミットを取得
      if latest_tag.empty?
        changelog = `git log --pretty=format:"%h %s"`
      else
        changelog = `git log #{latest_tag}..HEAD --pretty=format:"%h %s"`
      end
      puts "Changelog: #{changelog}"
    rescue => e
      puts "Error: #{e}"
    end
    setup_ci(provider: "travis")
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_KEY_CONTENT'],
      in_house: false,
      is_key_content_base64: true
    )
    match(
      git_basic_authorization: Base64.strict_encode64("#{ENV['GITHUB_ACTOR']}:#{ENV['GITHUB_TOKEN']}"),
      api_key: api_key,
      app_identifier: [
        'work.tkgstrator.thunder',
        'work.tkgstrator.thunder.packetTunnel'
      ],
      type: "appstore",
      readonly: is_ci
    )
    build_app(
      scheme: "ThunderSDKDemo",
      xcodeproj: "ThunderSDKDemo/ThunderSDKDemo.xcodeproj",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates",
      output_directory: "build",
      clean: true,
      silent: true,
      configuration: "Release"
      )
    upload_to_testflight(api_key: api_key, notify_external_testers: true, changelog: changelog.strip)
    increment_build_number(xcodeproj: "ThunderSDKDemo/ThunderSDKDemo∂.xcodeproj", build_number: latest_testflight_build_number + 1)
  end
end