name: Release Swift Package
on:
  pull_request:
    branches:
      - develop
      - master
    types: [closed]
jobs:
  deploy:
    name: Swift Package
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts
      - name: Build
        run: bun run dev
      - name: Swift
        uses: swiftyguard/setup-swift@v1 # Swiftのセットアップ
        with:
          swift-version: '5.10.1'  # 必要なSwiftのバージョンを指定
      - name: Run Tests
        run: swift test # テストの実行
